# Generated by Django 3.0.6 on 2021-01-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0004_article_tags'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='articles.Article'),
        ),
    ]
