ARTICLE_DOES_NOT_EXIST = 'An article with this slug does not exist.'
PROFILE_DOES_NOT_EXIST = 'The requested profile does not exist.'
COULD_NOT_DECODE_TOKEN = 'Invalid authentication. Could not decode token.'
NO_USER_FOUND = 'No user matching this token was found.'
USER_HAS_BEEN_DEACTIVATED = 'This user has been deactivated.'
