ARTICLE_DOES_NOT_EXIST = 'An article with this slug does not exist.'
PROFILE_DOES_NOT_EXIST = 'The requested profile does not exist.'
COULD_NOT_DECODE_TOKEN = 'Invalid authentication. Could not decode token.'
NO_USER_FOUND_WITH_TOKEN = 'No user matching this token was found.'
NO_USER_FOUND_WITH_USERNAME = 'No user matching this username was found.'
YOU_CANT_DELETE_OTHERS_COMMENT = "You can't delete others comment"
YOU_CANT_DELETE_OTHERS_ARTICLE = "You can't delete others article"
USER_HAS_BEEN_DEACTIVATED = 'This user has been deactivated.'
EMAIL_IS_REQUIRED = 'An email address is required to log in.'
PASSWORD_IS_REQUIRED = 'A password is required to log in.'
NO_USER_FOUND_WITH_EMAIL_PASSWORD = 'A user with this email and password was not found.'
CANT_FOLLOW_YOURSELF = 'You can not follow yourself.'
